apiVersion: v2
name: lifelike
description: Lifelike, a graph-powered knowledge mining platform. Turning big data into contextualized knowledge
home: https://lifelike.bio
icon: https://github.com/SBRG/lifelike/raw/main/appserver/assets/lifelike.png
type: application

version: 0.4.6
appVersion: 0.10.0

kubeVersion: ">=1.20.0-0"

keywords:
  - bioinformatics
  - bigdata
  - ai
  - biofoundry
  - knowledgegraph

sources:
  - https://github.com/SBRG/lifelike

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.16.2
    condition: postgresql.enabled
  - name: neo4j
    version: 4.4.3
    repository: https://neo4j-contrib.github.io/neo4j-helm
    condition: neo4j.enabled
  - name: elasticsearch
    version: 7.16.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: redis
    version: 16.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Lifelike website
      url: https://lifelike.bio
    - name: Lifelike Git repository
      url: https://github.com/SBRG/lifelike
  artifacthub.io/maintainers: |
    - name: David Regla
      email: darede@biosustain.dtu.dk
  artifacthub.io/prerelease: "true"
  artifacthub.io/screenshots: |
    - title: 'Lifelike: A graph-powered knowledge mining platform'
      url: https://lifelike.bio/assets/img/graph_embed/hero.jpg
