#!/bin/sh

echo "> 🧶 Running yarn lint.."
echo "This code assumes lint-stages being installed in client or globally."
echo "In case the command has not been found please run 'yarn install' in client folder"
cd client && yarn lint-staged

# ALTERNATIVELY - without extra dependencies and consistent with other services
#
## Runs linting on only files that are staged
#staged_files=$(getStaged client '\.(ts)$')
#
#echo "> 🧶 Running yarn lint.."
#echo ${staged_files} | xargs ng lint -- --tsConfig=tsconfig.json
