{{- if .Values.ingress.enabled -}}
{{- $fullName := include "lifelike.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{- include "lifelike.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
{{- with .Values.ingress }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className }}
  {{- end }}
  tls: {{- toYaml .tls | nindent 4 }}
  rules:
    - host: {{ .hostname | quote }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
{{- end }}
{{- end }}
