{{- if not (or .Values.postgresql.enabled .Values.postgresqlExternal.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lifelike.fullname" . }}
  labels: {{- include "lifelike.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  postgresql-password: {{ include "lifelike.postgresqlPassword" . | trim | b64enc | quote }}
{{- end -}}
