"""Add file annotation versioning

Revision ID: e58082ac34b8
Revises: 5b17cf4f72b0
Create Date: 2020-11-18 22:03:45.613422

"""
from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e58082ac34b8'
down_revision = '6f57a7647b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_annotations_version',
    sa.Column('creation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('hash_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('cause', sa.Enum('USER', 'USER_REANNOTATION', 'SYSTEM_REANNOTATION', name='annotationcause'), nullable=False),
    sa.Column('custom_annotations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('excluded_annotations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_annotations_version_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['appuser.id'], name=op.f('fk_file_annotations_version_user_id_appuser'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_annotations_version')),
    sa.UniqueConstraint('hash_id', name=op.f('uq_file_annotations_version_hash_id'))
    )
    op.create_index(op.f('ix_file_annotations_version_file_id'), 'file_annotations_version', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_annotations_version_user_id'), 'file_annotations_version', ['user_id'], unique=False)
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_annotations_version_user_id'), table_name='file_annotations_version')
    op.drop_index(op.f('ix_file_annotations_version_file_id'), table_name='file_annotations_version')
    op.drop_table('file_annotations_version')
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
