apiVersion: v1
kind: Service
metadata:
  name: {{ include "lifelike.fullname" . }}-frontend
  labels: {{- include "lifelike.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector: {{- include "lifelike.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
