{{- if .Values.pdfparser.autoScaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lifelike.fullname" . }}-pdfparser
  labels:
    {{- include "lifelike.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdfparser
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lifelike.fullname" . }}-pdfparser
  minReplicas: {{ .Values.pdfparser.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.pdfparser.autoScaling.maxReplicas }}
  metrics:
    {{- if .Values.pdfparser.autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pdfparser.autoScaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.pdfparser.autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.pdfparser.autoScaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
