apiVersion: v1
kind: Service
metadata:
  name: {{ include "lifelike.fullname" . }}-pdfparser
  labels: {{- include "lifelike.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdfparser
spec:
  type: {{ .Values.pdfparser.service.type | default }}
  ports:
    - port: {{ .Values.pdfparser.service.port }}
      targetPort: {{ .Values.pdfparser.service.port }}
      protocol: TCP
      name: http
  selector: {{- include "lifelike.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pdfparser
