name: Docker images

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  publish-images:
    name: Publish ${{ matrix.name }} Docker image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: appserver
            path: appserver
          - name: frontend
            path: client
          # - name: elasticsearch
          #   path: docker
          #   file: docker/elasticsearch.Dockerfile
          # - name: Grap data migrator
          #   path: graph-db
          #   image: lifelike-graph-db

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-${{ matrix.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor

      - name: Build and push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-${{ matrix.name }} image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
