name: Grpah DB Migrate

on:
  workflow_dispatch:
    inputs:
      neo4j_host:
        description: Neo4j target host to run migration
        type: string
        required: true
      neo4j_password:
        description: Neo4j password
        type: string
        required: true
      graphdb_migrator_tag:
        description: Tag of the graphdb-migrator image to use
        type: string
        required: true
        default: latest
      changelog:
        description: Path to the master changelog file
        type: string
        required: true
        default: 'lifelike-graph/changelog-master.xml'
      datafiles_prefix:
        description: Prefix of the datafiles in remote storage (stage/prod)
        type: choice
        required: true
        default: stage
        options:
          - stage
          - prod

jobs:
  migrate:
    name: Migrate Neo4j DB
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: ghcr.io/sbrg/lifelike-graphdb-migrator:${{ github.event.inputs.graphdb_migrator_tag }}
      options: --user root
      env:
        NEO4J_HOST: ${{ github.event.inputs.neo4j_host }}
        NEO4J_PASSWORD: ${{ github.event.inputs.neo4j_password }}
        CHANGELOG_FILE: ${{ github.event.inputs.changelog }}
        DATAFILES_PREFIX: ${{ github.event.inputs.datafiles_prefix }}
    steps:
      - uses: actions/checkout@v2
      - name: Copy changelog files
        run: cp -rp graph-db/changelog /liquibase/changelog
      - name: Run Liquibase migrations
        run: /liquibase/docker-entrypoint.sh update
