# Super Linter documentation: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint Code Base

on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
          VALIDATE_JSCPD: false
          FILTER_REGEX_EXCLUDE: (.*graph-db/.*)|(*\.csv)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
